apiVersion: v1
baseDomain: testing
compute:
- hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 2
controlPlane:
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 1
metadata:
  creationTimestamp: null
  name: tt
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineCIDR: 192.168.126.0/24
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  libvirt:
    URI: qemu+tcp://192.168.122.1/system
    network:
      if: tt0
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K3NlZ3dlc3QxZTlrYTJjdGtuemNhZmQ3ZXd6d2cydXcxNmI6MVY4VlEyMkg4UTk0OU1EMkk5M1RYQUhBQ0pGUEUyNFhZTkQxWU02RlpUMVdPMDM3QTcxTUM1MkQwM1ZKMUxPMQ==","email":"gwest@redhat.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K3NlZ3dlc3QxZTlrYTJjdGtuemNhZmQ3ZXd6d2cydXcxNmI6MVY4VlEyMkg4UTk0OU1EMkk5M1RYQUhBQ0pGUEUyNFhZTkQxWU02RlpUMVdPMDM3QTcxTUM1MkQwM1ZKMUxPMQ==","email":"gwest@redhat.com"},"registry.connect.redhat.com":{"auth":"NTIwNTUzNDl8dWhjLTFFOUtBMkNUS05aY2FmRDdFV1p3ZzJVVzE2YjpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSm1aalkzWm1JM05UVTJaamswWkdReU9UZGtNRFkxT1RGaE9XUmxOekJoWVNKOS5FdjRlRExVeGY4MEJLRTRsU0o1dkJCWTNmWnVJOHp1RVpWU3JZSElPZnJtaDVpbWFDeU1JX3VxWGkwYllhVGYxejdhdk1nXzVaRmhINEpGQ0ZvOXNWNURhWG83S2Rpb1FpLUlmYkhERzg2eFU0c2FMSzdZcndPc2Y1d2tEVGxTSV9VMTFzVGpLeUFidnA1WlhRaEc0cTZSVm05dE5INzdrOC1kTUFhTGRLYkV1blc0T1Uta1Q1ZWFEdWs5TW1PM1ZGeVYtQjVscnJJMFNQRXZzNU1HQUxsNncwQVRLN2NuZ2tmbVl1T0F0cWZZc2hfSVZfdVZXcjZCZWJzMV9jVVVZRnd1NjJpbWJiXy1BYmt5cWZPWmVCUloyclFsZnRsd1Z2bnRUMlRtdU1FRVV6cnFrRU9hZDBQZGhjdjlYeEFhcWRkY0l2SDhFWHV4WUQ5N3JTcGc0Q2o1Xy0za3F6Uzc5RnBpSGN3SHgzakIyaXJFNlp0cFowU1NhbE9WMEt2cUZHbzJGWDMyR2RMczZleW55Q0lkX2Fmd2tqYXR6dGNWb1k1eFU1d3dZOWFpa2lWbVZ2Z01XclJNeUNsZDJjaFVIbGRvTGhIRkNfVi1jSjFSNVdwRGhTc0F1OGFqM3RXYl9mNS1LZV9YS1U4SXVmYkhKS08tdFladUVnWkdGemZqdy03TF9pa1ZwQU9ZUUxXbUtjekVySVRnYnRzV2pwQ0EwaEg1TzhXT0V0OTJhLVhUbWdVdUZ1X0dIcVQxSlRZWWNFTEltWDZnZGphV2ZlTlNBY1ZQcVhDRXJ3cGphUk43SGxIdjJCTkZtRERUTmMyN3Vsc29lVUlCWEw5RzNOYkk4WnRsZVhZVkN5bGY1RzVHMEZhMGM5SFpvZXFzak1xTzdZUGhmVGhNaTdRWQ==","email":"gwest@redhat.com"},"registry.redhat.io":{"auth":"NTIwNTUzNDl8dWhjLTFFOUtBMkNUS05aY2FmRDdFV1p3ZzJVVzE2YjpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSm1aalkzWm1JM05UVTJaamswWkdReU9UZGtNRFkxT1RGaE9XUmxOekJoWVNKOS5FdjRlRExVeGY4MEJLRTRsU0o1dkJCWTNmWnVJOHp1RVpWU3JZSElPZnJtaDVpbWFDeU1JX3VxWGkwYllhVGYxejdhdk1nXzVaRmhINEpGQ0ZvOXNWNURhWG83S2Rpb1FpLUlmYkhERzg2eFU0c2FMSzdZcndPc2Y1d2tEVGxTSV9VMTFzVGpLeUFidnA1WlhRaEc0cTZSVm05dE5INzdrOC1kTUFhTGRLYkV1blc0T1Uta1Q1ZWFEdWs5TW1PM1ZGeVYtQjVscnJJMFNQRXZzNU1HQUxsNncwQVRLN2NuZ2tmbVl1T0F0cWZZc2hfSVZfdVZXcjZCZWJzMV9jVVVZRnd1NjJpbWJiXy1BYmt5cWZPWmVCUloyclFsZnRsd1Z2bnRUMlRtdU1FRVV6cnFrRU9hZDBQZGhjdjlYeEFhcWRkY0l2SDhFWHV4WUQ5N3JTcGc0Q2o1Xy0za3F6Uzc5RnBpSGN3SHgzakIyaXJFNlp0cFowU1NhbE9WMEt2cUZHbzJGWDMyR2RMczZleW55Q0lkX2Fmd2tqYXR6dGNWb1k1eFU1d3dZOWFpa2lWbVZ2Z01XclJNeUNsZDJjaFVIbGRvTGhIRkNfVi1jSjFSNVdwRGhTc0F1OGFqM3RXYl9mNS1LZV9YS1U4SXVmYkhKS08tdFladUVnWkdGemZqdy03TF9pa1ZwQU9ZUUxXbUtjekVySVRnYnRzV2pwQ0EwaEg1TzhXT0V0OTJhLVhUbWdVdUZ1X0dIcVQxSlRZWWNFTEltWDZnZGphV2ZlTlNBY1ZQcVhDRXJ3cGphUk43SGxIdjJCTkZtRERUTmMyN3Vsc29lVUlCWEw5RzNOYkk4WnRsZVhZVkN5bGY1RzVHMEZhMGM5SFpvZXFzak1xTzdZUGhmVGhNaTdRWQ==","email":"gwest@redhat.com"}}}'
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDWUsb0I159v27vSBuOOyQMX54iD2zuKZOOy+e5GRCJ3yONNr3Mkdyng67BNfsnvlf8kpgSi0yiaVGeXKSjkrY9YPHe0wkVW0UHZ9uZqYqgVdEzSG3Z0NNkrd/zp3jCztPad+q6iWb1R0iFlK7/h8NihOky9HXOustrtDwnvTgONwJnluxQp1zl86deKP0W9xx3Ky/Jobr3dbfOhJVK3qzF6OL6KaNjpT+hDYjh1OISzrx1jWLxFvZ4r7X2wbRhcNRyD5sTrxcs3z5Xdz/KRT0UhIj47CF4Heoiqtl/aQ5kdjpRqlmC2spJ9WZinsqbb6HhZ1i8Yd2ZycDQZF+S8n1n gwest@Glenns-MacBook-Pro.local
